import { desc, eq } from "drizzle-orm"
import { db, now } from "../db/client"
import { features, projects, runs } from "../db/schema"
import type { Feature, Project, QueueJob, Schedule } from "../types"
import { getEnabledAgent, runAgentStreaming } from "./agent.service"
import { appendLog } from "./runs.service"
import {
  gitAddAll,
  gitCommit,
  gitHasUncommittedChanges,
  gitMergeToDefault,
  gitPull,
  gitPush,
} from "./git.service"

export function buildPrompt(project: Project, feature: Feature): string {
  return `
You are an expert software developer working on the project: "${project.name}".

Your task is to implement the following feature:

**Feature Title:** ${feature.title}

**Feature Description:**
${feature.description ?? "No additional description provided. Use the title to guide your implementation."}

**Project Location:** ${project.localPath}

Instructions:
- Implement this feature completely and correctly
- Follow the existing code style and conventions in the project
- Create, modify, or delete files as needed
- Do not break any existing functionality
- Write clean, maintainable code
- Do not add TODO comments — implement fully
- Do not ask for clarification — make your best judgment and implement

Begin implementation now.
`.trim()
}

async function getProject(projectId: string): Promise<Project> {
  const row = await db.select().from(projects).where(eq(projects.id, projectId)).get()
  if (!row) throw new Error("PROJECT_NOT_FOUND")
  return row as any
}

async function getFeature(featureId: string): Promise<Feature> {
  const row = await db.select().from(features).where(eq(features.id, featureId)).get()
  if (!row) throw new Error("FEATURE_NOT_FOUND")
  return row as any
}

async function getRun(runId: string): Promise<any> {
  const row = await db.select().from(runs).where(eq(runs.id, runId)).get()
  if (!row) throw new Error("RUN_NOT_FOUND")
  return row
}

export async function executeFeatureRun(
  job: QueueJob,
  schedule: Schedule,
  opts?: { signal?: AbortSignal }
): Promise<void> {
  const project = await getProject(job.projectId)
  const feature = await getFeature(job.featureId)
  if (!job.runId) throw new Error("RUN_NOT_FOUND")
  const run = await getRun(job.runId)

  // Transition: queued → in_progress
  await db.update(features).set({ status: "in_progress", updatedAt: now() } as any).where(eq(features.id, feature.id)).run()
  await db.update(runs).set({ status: "running", startedAt: now() } as any).where(eq(runs.id, run.id)).run()

  try {
    const useGit = project.isGitRepo === true

    if (useGit && schedule.gitAutoPull) {
      await appendLog(run.id, "[GIT] Pulling latest changes...")
      await gitPull(project.localPath)
      await appendLog(run.id, "[GIT] Pull complete.")
    }

    const prompt = buildPrompt(project, feature)
    await appendLog(run.id, "[AGENT] Starting...")
    const selectedAgentId =
      schedule.agentId ??
      (await getEnabledAgent())?.id ??
      null
    if (!selectedAgentId) {
      throw new Error("AGENT_NOT_FOUND")
    }
    await db.update(runs).set({ agentId: selectedAgentId } as any).where(eq(runs.id, run.id)).run()
    const agentResult = await runAgentStreaming(prompt, project.localPath, {
      agentId: selectedAgentId,
      signal: opts?.signal,
      onOutput: async (chunk) => {
        await appendLog(run.id, chunk)
      },
    })
    console.log(`Agent result for run ${run.id}:`, agentResult)
    if (!agentResult.success) {
      if (agentResult.error === "CANCELLED") throw new Error("CANCELLED")
      throw new Error(`Agent failed: ${agentResult.error ?? "unknown error"}`)
    }
    await appendLog(run.id, "[AGENT] Completed successfully.")

    let commitHash: string | undefined
    if (useGit && schedule.gitAutoCommit) {
      await gitAddAll(project.localPath)
      const hasChanges = await gitHasUncommittedChanges(project.localPath)
      if (hasChanges) {
        const message = `feat: ${feature.title}\n\nGenerated by RepoPilot`
        commitHash = await gitCommit(project.localPath, message)
        await db.update(runs).set({ commitHash } as any).where(eq(runs.id, run.id)).run()
        await appendLog(run.id, `[GIT] Committed: ${commitHash}`)
      } else {
        await appendLog(run.id, "[GIT] No file changes detected — skipping commit.")
      }
    }

    if (useGit && schedule.gitAutoPush && commitHash) {
      try {
        await appendLog(run.id, "[GIT] Pushing to remote...")
        await gitPush(project.localPath)
        await db.update(runs).set({ pushedAt: now() } as any).where(eq(runs.id, run.id)).run()
        await appendLog(run.id, "[GIT] Push succeeded.")
      } catch (pushErr) {
        await appendLog(run.id, `[GIT WARNING] Push failed: ${(pushErr as any)?.message ?? String(pushErr)}`)
      }
    }

    if (useGit && schedule.gitAutoMerge && schedule.gitAutoPush) {
      try {
        const target = project.defaultBranch ?? "main"
        await appendLog(run.id, `[GIT] Merging into ${target}...`)
        await gitMergeToDefault(project.localPath, target)
        await db.update(runs).set({ mergedAt: now() } as any).where(eq(runs.id, run.id)).run()
        await appendLog(run.id, `[GIT] Merged to ${target} successfully.`)
      } catch (mergeErr) {
        await appendLog(run.id, `[GIT WARNING] Merge failed: ${(mergeErr as any)?.message ?? String(mergeErr)}`)
      }
    }

    await db.update(features).set({ status: "review", updatedAt: now() } as any).where(eq(features.id, feature.id)).run()
    await db.update(runs).set({ status: "success", completedAt: now() } as any).where(eq(runs.id, run.id)).run()
  } catch (error) {
    const message = (error as any)?.message ?? String(error)
    if (message === "CANCELLED") {
      await db.update(features).set({ status: "pending", updatedAt: now() } as any).where(eq(features.id, feature.id)).run()
      await db
        .update(runs)
        .set({ status: "skipped", errorMessage: "Cancelled by user", completedAt: now() } as any)
        .where(eq(runs.id, run.id))
        .run()
      await appendLog(run.id, "[AGENT] Cancelled by user.")
      return
    }

    await db.update(features).set({ status: "failed", updatedAt: now() } as any).where(eq(features.id, feature.id)).run()
    await db
      .update(runs)
      .set({ status: "failed", errorMessage: message, completedAt: now() } as any)
      .where(eq(runs.id, run.id))
      .run()
    await appendLog(run.id, `[ERROR] ${message}`)

    const lastTwo = await db
      .select()
      .from(runs)
      .where(eq(runs.featureId, feature.id))
      .orderBy(desc(runs.startedAt))
      .limit(2)
      .all()
    const lastTwoBothFailed =
      lastTwo.length === 2 &&
      lastTwo[0]!.status === "failed" &&
      lastTwo[1]!.status === "failed"
    if (lastTwoBothFailed) {
      await db
        .update(features)
        .set({ frozen: true, updatedAt: now() } as any)
        .where(eq(features.id, feature.id))
        .run()
      await appendLog(
        run.id,
        "[FEATURE] Frozen because the last two runs failed. Unfreeze on the feature page when you want automation to pick it up again."
      )
    }
  }
}

